CREATE TABLE IF NOT EXISTS public.users (
    id             int4 GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username       varchar(50)  NOT NULL UNIQUE,
    password_hash  varchar(255) NOT NULL,
    email          varchar(100) NOT NULL UNIQUE,
    created_at     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.exhibitions (
    id              int4 GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title           varchar(255)  NOT NULL,
    description     text,
    description2    text,
    description3    text,
    price           numeric(18,2) NOT NULL,
    total_capacity  int4          NOT NULL,
    availability    int4          NOT NULL,
    CONSTRAINT exhibitions_price_nonneg  CHECK (price >= 0),
    CONSTRAINT exhibitions_capacity_pos  CHECK (total_capacity >= 0),
    CONSTRAINT exhibitions_availability  CHECK (availability BETWEEN 0 AND total_capacity)
);

CREATE TABLE IF NOT EXISTS public.purchased_tickets (
    id             uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        int4         NOT NULL REFERENCES public.users(id),
    exhibition_id  int4         NOT NULL REFERENCES public.exhibitions(id),
    unique_code    varchar(100) NOT NULL UNIQUE,
    price_paid     numeric(10,2) NOT NULL CHECK (price_paid >= 0),
    purchase_date  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_purchased_tickets_user
    ON public.purchased_tickets (user_id, purchase_date DESC);

CREATE TABLE IF NOT EXISTS public.gallery (
    id          int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_ita   varchar NOT NULL,
    title_eng   varchar NOT NULL,
    site        varchar,
    "date"      varchar,
    description text,
    alt_image   varchar,
    url_image   varchar NOT NULL
);
