name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - run: dotnet build RobertDoisneau.WebApi/RobertDoisneau.WebApi.slnx --configuration Release
      - run: dotnet test RobertDoisneau.WebApi/RobertDoisneau.WebApi.slnx --configuration Release --no-build
